# Generated by Django 3.1.7 on 2021-03-17 04:16

from django.db import migrations
import json
import os
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'restaurants.json'


def load_data(apps, schema_editor):
    Shop = apps.get_model('my_shop', 'Shop')
    apps_path = Path(__file__).parents[3]
    jsonfile = os.path.join(apps_path, 'dump', DATA_FILENAME)

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Shop(name=name, location = location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

