# Generated by Django 3.1.7 on 2021-03-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0003_auto_20210321_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': [('can_view_shop_list', 'Can view shop list'), ('can_edit_shop_name', 'Can edit shop name')]},
        ),
    ]
